### ISSUE TITLE
Create new issue on new release of GAD (TODO description)

### ISSUE THREAD

**Issue by kat-kan** [kat-kan/kawqa-gad-playwright#105]
## ✅ Issue reporting checklist

- [x] I created a descriptive title for this issue
- [x] I checked that it hasn't been reported yet
- [x] I assigned the issue or added `help-wanted` label
- [x] I added appropriate labels

**Comment by kat-kan** [comment]
Done
