### ISSUE TITLE
Github workflow standards && project standards to be established

### ISSUE THREAD

**Issue by bugITwhisperer** [kat-kan/kawqa-gad-playwright#3]
### Challenge
Currently, we don't have any rules established regarding GitHub workflow standards, and project standards.

---
### GitHub workflow standards
1. Contributor standards file, so called 'Contribution Guidelines' describing:
- [ ] how to start working/contributing to the project
- [ ] issue raising process
- [ ] PR approval/code review process incl. PR merging & branch deletion

2. Project settings - Issue's description && Pull Request's description
- [x] issue template with description guidelines  -> #15
- [x] pull request template with description guidelines  -> #16 

---
### Project standards
1. file: README.md
Project's README that includes:
- [ ] repository/project main goals
- [ ] list of project contributors
- [x] how-to work with repository: installation prerequisites; installation steps; how to run tests → #4
- [ ] redirections to internal: CONTRIBUTION, DECISION_LOG files, and what the files contain - short description
- [ ] redirections to 2 other repositories in which test cases are used, and how they will be used there - short description: https://github.com/kat-kan/kawqa-gad-docs, https://github.com/kat-kan/kawqa-gad-postman

2. file: DECISION_LOG.md
Decision log which will cover:
- [ ] preparing decision log
- [ ] short explanation why Playwright was selected for writing automation API checks
- [ ] decision regarding project structure
- [ ] coding standards, incl. tools for static code analysis #9
- [x] branches naming convention #8 
- [ ] commits naming convention

3. file: CHANGELOG.md (do we need this? - currently no)
Change log with the list of main commits that introduced important changes. Not sure if we need this or not.

4. file: LICENSE.md (do we need this? - no)
Info on the license we use. Not sure if we need this or not.

if there are any other items that we should cover, let's add them to the list :) and let's discuss those either here or on our Discord's channel after making some research, and providing a short summary of our findings on our notion page
